parameters:
    app.gitlab.group.service.class:     ClientBundle\Service\Gitlab\GroupService
    app.gitlab.project.service.class:   ClientBundle\Service\Gitlab\ProjectService
    app.gitlab.user.service.class:      ClientBundle\Service\Gitlab\UserService

services:
    app.gitlab.group.service:
        class: %app.gitlab.group.service.class%
        arguments:
            - '@gitlab.client'
            - %gitlab_token%

    app.gitlab.project.service:
        class: %app.gitlab.project.service.class%
        arguments:
            - '@gitlab.client'
            - %gitlab_token%

    app.gitlab.user.service:
        class: %app.gitlab.user.service.class%
        arguments:
            - '@gitlab.client'
            - %gitlab_token%
