parameters:
    app.developer.service.class: AppBundle\Service\DeveloperService
    app.group.service.class: AppBundle\Service\GroupService
    app.project.service.class: AppBundle\Service\ProjectService

services:
    app.developer.service:
        class: %app.developer.service.class%
        arguments:
            - '@app.gitlab.user.service'
            - '@app.developer.mapping'

    app.group.service:
        class: %app.group.service.class%
        arguments:
            - '@app.gitlab.group.service'
            - '@app.group.mapping'
            - '@app.group.repository'

    app.project.service:
        class: %app.project.service.class%
        arguments:
            - '@app.gitlab.project.service'
            - '@app.project.mapping'
            - '@app.project.repository'
            - '@app.group.repository'
