parameters:
    app.commit.service.class: AppBundle\Service\CommitService
    app.developer.service.class: AppBundle\Service\DeveloperService
    app.group.service.class: AppBundle\Service\GroupService
    app.merge_request.service.class: AppBundle\Service\MergeRequestService
    app.project.service.class: AppBundle\Service\ProjectService

services:
    app.developer.service:
        class: %app.developer.service.class%
        arguments:
            - '@app.gitlab.user.service'
            - '@app.developer.mapping'
            - '@app.developer.repository'
            - '@app.project.repository'

    app.group.service:
        class: %app.group.service.class%
        arguments:
            - '@app.gitlab.group.service'
            - '@app.group.mapping'
            - '@app.group.repository'

    app.project.service:
        class: %app.project.service.class%
        arguments:
            - '@app.gitlab.project.service'
            - '@app.project.mapping'
            - '@app.project.repository'
            - '@app.group.repository'

    app.merge_request.service:
        class: %app.merge_request.service.class%
        arguments:
            - '@app.gitlab.merge_request.service'
            - '@app.merge_request.mapping'
            - '@app.merge_request.repository'

    app.commit.service:
        class: %app.commit.service.class%
        arguments:
            - '@app.gitlab.merge_request.service'
            - '@app.commit.mapping'
