parameters:
    gitlab.client.class: ClientBundle\Client\GitlabClient

services:
    gitlab.client:
        class: %gitlab.client.class%
        arguments:
            - "@csa_guzzle.client.gitlab_api"
            - %gitlab_token%
