parameters:
    app.developer.mapping.class:  AppBundle\Service\Mapping\DeveloperMapping
    app.group.mapping.class:      AppBundle\Service\Mapping\GroupMapping
    app.project.mapping.class:    AppBundle\Service\Mapping\ProjectMapping

services:
    app.developer.mapping:
        class: %app.developer.mapping.class%

    app.group.mapping:
        class: %app.group.mapping.class%

    app.project.mapping:
        class: %app.project.mapping.class%
