parameters:
    app.developer.repository.class: AppBundle\Repository\DeveloperRepository

services:
    app.developer.repository:
        class: %app.developer.repository.class%
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments: ['AppBundle:Developer']
